# Generated by Django 4.1.6 on 2023-03-12 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_customerbalance_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='balances', to='bets.customer')),
                ('home_bet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='balances', to='core.homebet')),
            ],
            options={
                'db_table': 'customer_balance',
                'unique_together': {('customer', 'home_bet')},
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('profit_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bets', to='bets.customerbalance', unique=True)),
            ],
            options={
                'db_table': 'bet',
            },
        ),
    ]
