# Generated by Django 4.1.6 on 2023-03-12 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bets', to='bets.customerbalance'),
        ),
    ]
