# Generated by Django 4.1.6 on 2023-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_alter_bet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbalance',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
