FROM python:3.11-slim-bookworm as intermediate

# FROM python:3.11-slim-buster

# Keeps Python from generating .pyc files in the container
ENV PYTHONUNBUFFERED=1

# Turns off buffering for easier container logging
ENV PYTHONDONTWRITEBYTECODE=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev \
    build-essential \
    libssl-dev \
    libffi-dev \
    libcurl4-openssl-dev \
    netcat-openbsd \
&& rm -rf /var/lib/apt/lists/*

ENV VIRTUAL_ENV=/usr/app/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install uv

COPY requirements /tmp/requirements

RUN uv pip install -Ur /tmp/requirements/development.txt

ENV APP_HOME=/app

WORKDIR $APP_HOME

COPY postgres-healthy.sh /tmp/postgres-healthy.sh
COPY . /app/
COPY fixtures/* /app/fixtures/

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
RUN mkdir -p $APP_HOME && chown -R user:user $APP_HOME

RUN chown -R user:user $APP_HOME
USER user

ENTRYPOINT ["bash", "/tmp/postgres-healthy.sh"]

# CMD python manage.py migrate --mv && python manage.py runserver 0:8000
CMD python manage.py runserver 0:8000
