# Generated by Django 4.1.6 on 2023-03-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbalance',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='customerbalance',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerbalance',
            name='home_bet',
        ),
        migrations.RemoveField(
            model_name='customerbethistory',
            name='balance',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerBalance',
        ),
        migrations.DeleteModel(
            name='CustomerBetHistory',
        ),
    ]
