# Generated by Django 4.2.2 on 2023-06-06 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.CharField(max_length=50)),
                ('prediction', models.FloatField(default=0.0)),
                ('amount', models.FloatField()),
                ('multiplier', models.FloatField(null=True)),
                ('multiplier_result', models.FloatField(blank=True, null=True)),
                ('profit_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('bet_type', models.CharField(default='automatic', max_length=10)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bets', to='customers.customerbalance')),
            ],
            options={
                'db_table': 'bet',
                'unique_together': {('balance', 'external_id')},
            },
        ),
    ]
