# Generated by Django 4.1.7 on 2023-04-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_remove_bet_prediction_round_alter_bet_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(default='automatic', max_length=10),
        ),
    ]
