# Generated by Django 4.1.7 on 2023-04-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbalance',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customerbalance',
            name='username',
        ),
    ]
