# Generated by Django 4.2.5 on 2023-10-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_homebetgame_unique_together'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customersession',
            unique_together={('customer', 'home_bet')},
        ),
    ]
