# Generated by Django 4.2.5 on 2023-11-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbalance',
            name='currency',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
