# Generated by Django 4.2.5 on 2023-10-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customersession_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customersession',
            unique_together=set(),
        ),
    ]
