# Generated by Django 4.2.5 on 2023-10-20 21:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plan_with_ai'),
        ('customers', '0002_customerplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='customers.customer')),
                ('home_bet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='core.homebet')),
            ],
            options={
                'db_table': 'customer_session',
                'unique_together': {('customer', 'home_bet', 'is_active')},
            },
        ),
    ]
