# Generated by Django 4.2.5 on 2023-10-28 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrashApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('hash_str', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('version', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'crash_app',
            },
        ),
        migrations.CreateModel(
            name='CrashGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'crash_game',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='HomeBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'homebet',
            },
        ),
        migrations.CreateModel(
            name='HomeBetGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('limits', models.JSONField(default=dict)),
                ('crash_game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_bets', to='core.crashgame')),
                ('home_bet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='core.homebet')),
            ],
            options={
                'db_table': 'home_bet_game',
                'unique_together': {('home_bet', 'crash_game')},
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('duration_in_days', models.IntegerField()),
                ('with_ai', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('crash_apps', models.ManyToManyField(related_name='plans', to='core.crashapp')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans', to='core.currency')),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.AddField(
            model_name='crashapp',
            name='home_bet_games',
            field=models.ManyToManyField(related_name='crash_apps', to='core.homebetgame'),
        ),
        migrations.CreateModel(
            name='Multiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('multiplier_dt', models.DateTimeField()),
                ('home_bet_game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='multipliers', to='core.homebetgame')),
            ],
            options={
                'db_table': 'home_bet_multiplier',
                'indexes': [models.Index(fields=['home_bet_game', 'multiplier_dt'], name='home_bet_mu_home_be_2d9cef_idx')],
            },
        ),
    ]
