# Generated by Django 4.1.7 on 2023-05-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebetmultiplier',
            name='number_of_players',
        ),
        migrations.AddIndex(
            model_name='homebetmultiplier',
            index=models.Index(fields=['home_bet', 'multiplier_dt'], name='homebet_mul_home_be_3e1a0c_idx'),
        ),
    ]
