# Generated by Django 4.2.5 on 2023-10-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='multiplier',
            name='updated_at',
        ),
    ]
