# Generated by Django 4.2.5 on 2023-10-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homebetgame',
            unique_together={('home_bet', 'crash_game')},
        ),
    ]
