# Generated by Django 4.2.2 on 2023-10-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='with_ai',
            field=models.BooleanField(default=False),
        ),
    ]
