# Generated by Django 4.2.5 on 2023-10-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plan_with_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebet',
            name='amount_multiple',
            field=models.FloatField(default=100.0),
        ),
    ]
